### ISSUE TITLE
ansible script to install nwg-displays on debian

### ISSUE THREAD

**Issue by ronsmits** [nwg-piotr/nwg-displays#65]
The following expects `sway` already installed (`apt install -y sway`), then with ansible playbook run this playbook:
```
- hosts: localhost
  become: yes

  pre_tasks:
  - name: upgrade OS
    apt:
      upgrade: yes
      update_cache: yes
    changed_when: False

  tasks:
    - name: install needed packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - python3-setuptools
        - python3-gi
        - gir1.2-gtk-3.0
        - libgtk-layer-shell-dev
        - python3-i3ipc
        - greetd
        - python3-build
        - python3-installer
        - python3-wheel


    - name: clone nwg-displays
      git:
        repo: "https://github.com/nwg-piotr/{{ item }}.git"
        dest: /tmp/{{ item }}
        update: false
      loop:
        - nwg-displays

    - name: install nwg-displays
      become: yes
      command: ./install.sh
      args:
        chdir: /tmp/nwg-displays
```
